import type { Metadata } from "next";
import "@/app/globals.css";
import "github-markdown-css/github-markdown.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Raha | 技術共有サイト",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
