import type { Metadata } from "next";
import "../globals.css";
import "github-markdown-css/github-markdown.css";
import Header from "@/components/layouts/Header/Header";
import { cookies } from "next/headers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Raha | 技術共有サイト",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookiesStore = await cookies();
  const token = cookiesStore.get("token")?.value || null;

  return (
    <html lang="en">
      <body>
        <Header token={token} />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
